services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod     # pakai Dockerfile khusus prod (nginx static)
    networks:
      - net
      - proxy

  backend:
    networks:
      - net
      - proxy

  ml:
    networks:
      - net
      - proxy 

networks:
  proxy:
    external: true