services:
  backend:
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      NODE_ENV: development

  ml:
    ports:
      - "8000:8000"
    volumes:
      - ./ML:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev      # pakai Dockerfile khusus dev (npm start)
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      REACT_APP_API_URL: http://localhost:5000/api
      CHOKIDAR_USEPOLLING: "true"